src/trial/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

src/trial/pdfmr/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pdfmr"

urlpatterns = [
    path('top/', views.top, name='top'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('list/', views.ListView.as_view(), name='list'),
    path('dell_file/', views.dell_file, name='dell_file'),
]

src/trial/trial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pdfmr/', include('pdfmr.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/trial/accounts/models.py
from django.db import models

# Create your models here.

src/trial/pdfmr/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

# Create your models here.
attach = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='添付ファイル',
        validators=[FileExtensionValidator(['pdf', ])],
    )

src/trial/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 


class LoginForm(AuthenticationForm):
    """ログオンフォーム"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
            

src/trial/pdfmr/forms.py
from django import forms
from django.conf import settings
from django.core.files.storage import default_storage
from upload_validator import FileTypeValidator
import os, random, string
from .custom_widgets import CustomClearableFileInput  # カスタムウィジェットをインポート


def create_dir(n):
    """一時フォルダ名生成関数"""
    return 'pdf/' + ''.join(random.choices(string.ascii_letters + string.digits, k=n))


def save(uploaded_files):
    temp_dir = os.path.join(settings.MEDIA_ROOT, create_dir(10))  # 一時フォルダの生成
    for pdf in uploaded_files:
        default_storage.save(os.path.join(temp_dir, pdf.name), pdf)  # 一時フォルダにPDFを保存
    return temp_dir


class UploadForm(forms.Form):
    """PDFアップロード用フォームの定義
       saveメソッドはアップロードしたPDFを一時フォルダに保存する。
    """
    document = forms.FileField(label="PDFアップロード",
                               widget=CustomClearableFileInput(attrs={'multiple': True,
                                                                      'title': 'Choose PDF files to upload',
                                                                      # title属性を追加
                                                                      'placeholder': 'Select files'
                                                                      # placeholder属性を追加
                                                                      }),
                               validators=[FileTypeValidator(allowed_types=['application/pdf'])])

src/trial/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView)
from .forms import LoginForm


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'accounts/login.html'

src/trial/pdfmr/views.py
import logging

from django.shortcuts import render
from django.views import generic  # FormViewを利用するため
from django.contrib.auth.mixins import LoginRequiredMixin  # ログオンユーザのみアクセス可とするために利用する
from django.conf import settings  # settings.pyの定義内容を利用するため
from .forms import UploadForm  # forms.pyで定義したUploadFormをインポート
from django.core.files.storage import default_storage  # ファイルオブジェクト操作のためdefault_storageを利用する
from .utils import create_excel
from django.contrib.auth.decorators import login_required
import shutil
import os

logger = logging.getLogger(__name__)

def top(request):
    return render(request, 'pdfmr/top.html')

class UploadView(LoginRequiredMixin, generic.FormView):
    form_class = UploadForm
    template_name = 'pdfmr/upload_form.html'

    def form_valid(self, form):
        user_name = self.request.user.username  # ログオンユーザ名の取得
        user_dir = os.path.join(settings.MEDIA_ROOT, "excel", user_name)  # ユーザディレクトリパスの生成
        if not os.path.isdir(user_dir):  # ユーザディレクトリの作成
            os.makedirs(user_dir)
        # アップロードファイルの情報をログに出力
        upload_files = self.request.FILES.getlist('document')
        logger.debug(f"Uploaded files: {upload_files}")
        if not upload_files:
            logger.error("No files were uploaded.")
            return self.form_invalid(form)

        temp_dir = form.save(upload_files)  # upload一時フォルダの取得
        err = create_excel(temp_dir, user_name)  # PDF->Excelデータ生成
        if err:
            shutil.rmtree(temp_dir)  # upload一時フォルダの削除
            context = {
                'err': err,
            }
            return render(self.request, 'pdfmr/complete.html', context)
        shutil.rmtree(temp_dir)  # upload一時フォルダの削除
        _, file_list = default_storage.listdir(os.path.join(settings.MEDIA_ROOT, "excel", user_name))
        message = "正常終了しました。"
        context = {
            'file_list': file_list,
            'user_name': user_name,
            'message': message,
        }
        return render(self.request, 'pdfmr/complete.html', context)

    def form_invalid(self, form):
        logger.debug(f"Form errors: {form.errors}")
        return render(self.request, 'pdfmr/upload_form.html', {'form': form})


class ListView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'pdfmr/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # 承継元のメソッドを呼び出す
        """自分が作成したExcelファイルだけを一覧表示"""
        login_user_name = self.request.user.username
        if not default_storage.exists(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name)):
            warning_message = "このユーザでは一度もファイル作成が行われていません。"
            context = {
                'warning_message': warning_message,
            }
            return context
        file_list = default_storage.listdir(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name))[1]
        context = {
            'file_list': file_list,
            'login_user_name': login_user_name,
        }
        return context


@login_required
def dell_file(request):
    checks_value = request.POST.getlist('checks')  # CheckBox＝Onのファイル名を取得
    login_user_name = request.user.username  # ログオンユーザ名を取得

    # Excelファイルの格納パスを取得
    if checks_value:
        for file in checks_value:
            path = os.path.join(settings.MEDIA_ROOT, "excel", login_user_name, file)
            default_storage.delete(path)  # CheckBox=ONのファイルをサーバから削除
        return render(request, 'pdfmr/delete.html', {'checks_value': checks_value})
    else:
        login_user_name = request.user.username
        file_list = default_storage.listdir(os.path.join(settings.MEDIA_ROOT, "excel", login_user_name))[1]
        warning_message = "削除対象ファイルが選択されていません。"

        context = {
            'file_list': file_list,
            'login_user_name': login_user_name,
            'warning_message': warning_message,
        }
        return render(request, 'pdfmr/list.html', context)

src/trial/templates/accounts/login.html
{% load static %}

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>PDF to Excel</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.18/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.18/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.18/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.18/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'AdminLTE-2.4.18/plugins/iCheck/square/blue.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <h1 style="font-weight: bold;">PDF to Excel
        <small style="font-size: 12px;"> —— by yu-aoki </small>
      </h1>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg"><b>ログオン画面</b></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- jQuery 3 -->
  <script src="{% static 'AdminLTE-2.4.18/bower_components/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{% static 'AdminLTE-2.4.18/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'AdminLTE-2.4.18/plugins/iCheck/icheck.min.js' %}"></script>
</body>
</html>

src/trial/templates/pdfmr/complete.html
{% extends './base.html' %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>一覧画面</h1>
  <ol class="breadcrumb">
    <li><a href="{% url 'pdfmr:top' %}"><i class="fa fa-dashboard"></i> ホーム</a></li>
    <li class="active">ダッシュボード</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
<!-- Small boxes (Stat box) -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title"> <b>PDF→Excel変換処理結果</b></h3>
      </div>
      <div class="box-body">
        <div class="card-body">
          {% if message  %}
          <div class="callout callout-info">
            {{message}}
          </div>
          {% endif %}
          {% if err  %}
          <div class="callout callout-danger">
              {{err |safe}}
          </div>
          {% endif %}
        </div>
        <hr>
        <div class="text-center">
          <a href="{% url 'pdfmr:top' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
</div>

<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}

src/trial/templates/pdfmr/delete.html
{% extends './base.html' %}
{% load bootstrap4 %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>Excelファイル削除完了</h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
      <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">選択した Excelファイル削除が完了しました。</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
            <hr>
            <div class="card-body">
              <b> 削除したファイル一覧</b><br>
              <ul class="list-group">
                {% for file in  checks_value　%}
                <li class="list-group-item  alert alert-success alert-dismissible" role="alert">{{file}}</li>
                {% endfor %}
              </ul>
              <hr>
            </div>
            <div class="text-center">
              <a href="{% url 'pdfmr:top' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
              <a href="{% url 'pdfmr:list' %}" class="btn btn-primary btn-sm" role="button">一覧表示画面へ</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  </div>

<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}

src/trial/templates/pdfmr/list.html
{% extends './base.html' %}
{% load bootstrap4 %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>一覧画面</h1>
    <ol class="breadcrumb">
      <li><a href="{% url 'pdfmr:top' %}"><i class="fa fa-dashboard"></i> ホーム</a></li>
      <li class="active">ダッシュボード</li>
    </ol>
  </section>
  <!-- Main content -->
  <section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"> <b>生成済みExcelファイル一覧</b></h3>
          </div>
          <div class="box-body">
            <div class="card-body">
              <hr>
            <!--ここから下を新規追加 -->
            <form action="{% url 'pdfmr:dell_file' %}" name="form" method="post">
              {% csrf_token %}
              <label>
                <input type="checkbox" name="all" onClick="AllChecked();" />全て選択
              </label><br>
              <!--ここまでを新規追加 -->

              {% for file in file_list %}
              <label>
                <input type="checkbox" name="checks" value="{{file}}" onClick="DisChecked();" />
                <a href="http://127.0.0.1:8000/media/excel/{{login_user_name}}/{{file}}">{{file}}</a>
              </label>
              <br> 
              {% endfor %}
            <!--ここから下を新規追加 -->
              <input type="submit" id="button" name="button"  class="btn btn-sm btn-danger" value="削除">
            </form>
            {% if warning_message %}
            <hr>
            <div class="alert alert-warning alert-dismissible" role="alert">
              <p>{{warning_message}}</p>
            </div>
            {% endif %}
            <hr>
            <!--ここまでを新規追加 -->
              <div class="text-center">
                <a href="{% url 'pdfmr:top' %}" class="btn btn-primary btn-sm" role="button">戻る</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}

src/trial/templates/pdfmr/top.html
<!--top.htmlの冒頭-->

<!-- ===== ここから追加====== -->
{% extends './base.html' %}
{% block content %}
<!-- ===== ここまで追加====== -->

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <!-- ============================== ここから以下を追加 ============================== -->
      <!-- Content Header (Page header) -->
      <section class="content-header">
          <h1>ダッシュボード</h1>
          <ol class="breadcrumb">
              <li><a href="#"><i class="fa fa-dashboard"></i> ホーム</a></li>
              <li class="active">ダッシュボード</li>
          </ol>
      </section>
      <!-- Main content -->
      <section class="content">
          <!-- Small boxes (Stat box) -->
          <div class="row">
              <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-aqua">
                      <div class="inner">
                          <h4>PDFtoExcel</h4>
                          <p>PDF→Excel変換</p>
                      </div>
                      <div class="icon">
                          <i class="ion ion-android-share"></i>
                      </div>
                      <a href="{% url 'pdfmr:upload' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                  </div>
              </div>
              <!-- ./col -->
              <div class="col-lg-3 col-xs-6">
                  <!-- small box -->
                  <div class="small-box bg-green">
                      <div class="inner">
                          <h4>Excel管理画面</h4>
                          <p>生成済みExcelファイルの管理</p>
                      </div>
                      <div class="icon">
                          <i class="ion ion-document"></i>
                      </div>
                      <a href="{% url 'pdfmr:list' %}" class="small-box-footer">管理画面へ移動 <i class="fa fa-arrow-circle-right"></i></a>
                  </div>
              </div>
          </div>
          <!-- /.row -->
          <!-- Main row -->
          <div class="row">
              <!-- Left col -->
              <section class="col-lg-7 connectedSortable"></section>
              <!-- /.Left col -->
              <!-- right col (We are only adding the ID to make the widgets sortable)-->
              <!-- right col -->
          </div>
          <!-- /.row (main row) -->
      </section>
      <!-- /.content -->
      <!-- ============================== ここまでを追加 ============================== -->
    </div>
    <!-- /.content-wrapper -->
<!-- ===== ここから追加====== -->
{% endblock content %}
<!-- ===== ここから追加====== -->

src/trial/templates/pdfmr/upload_form.html
{% extends './base.html' %}
{% load static %}
{% block content %}
 
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>アップロード画面</h1>
  <ol class="breadcrumb">
    <li><a href="{% url 'pdfmr:top' %}"><i class="fa fa-dashboard"></i> ホーム</a></li>
    <li class="active">ダッシュボード</li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"><b>PDF->Excel変換</b></h3>
          <p>※PDFは複数ファイルを一括でアップロードすることができます。</p>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <hr>
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
              <div class="form-group col-sm-5">
                {{ form.document.label_tag }}  <!-- ラベルを表示 -->
                {{ form.document.errors }}  <!-- エラーメッセージの詳細表示 -->
                {{ form.document }}
              </div>

            <button type="submit" class="btn btn-sm btn-primary">アップロード</button>
          </form>
          <!-- ここから追加 -->
          {% if form.errors %}<hr>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <p>ファイルの種類を確認してください。<br>PDFファイル以外はアップロードできません。</p>
            <ul>
              {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
              {% endfor %}
              {% for field, errors in form.errors.items %}
              {% for error in errors %}
              <li>{{ field }}: {{ error }}</li>
              {% endfor %}
              {% endfor %}
            </ul>
          </div>
          {% endif %}
          <!-- ここまで追加 -->
        </div>
      </div>
    </div>
  </div>
</section>
</div>
<!-- /.content -->
<!-- /.content-wrapper -->
{% endblock content %}